### ISSUE TITLE
3.4: Confusing Planets List

### ISSUE THREAD

**Issue by gildedgardenia** [LaunchCodeEducation/csharp-web-development#103]
## Link

https://education.launchcode.org/csharp-web-development/chapters/control-flow-and-collections/list.html#list-methods

## Description

In the section on List Methods, we use a list of planets to demo different methods and how devs can use them. At the end of this section, we say that the count of our planets list would be 9. This is because in the table of methods we add "Pluto" to the list, however, it reads as though the students should be looking at the code sample above the table with 8 planets. Some clarification might need to be added the text as to whether they should look at the list after the table or in the code sample.

**Comment by jimflores5** [comment]
Resolved planet count.
