### ISSUE TITLE
Authentication and Authorization

### ISSUE THREAD

**Issue by scottkuhl** [LaunchCodeEducation/csharp-web-development#69]
At some point the projects need to include identity management. This includes a project that has users register and log in and maybe how to make minor extensions to it like capturing the users first and last name.  The project should also connect the classes they create, like a pizza order, to the classes that are part of the identity framework, like tracking which user placed the order.  Almost all student projects require this feature and they end up struggling with it instead of focusing on their project.

It looks like the Java track includes this, so I am hoping we can get it into the C# track as well.

[Identity management documentation.](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity)

[A guide I created for extending Identity Management.](https://medium.com/@scottkuhl/extending-asp-net-core-2-2-identity-management-c3cc657cc448)

**Comment by gildedgardenia** [comment]
Thanks for opening this issue! I have started a scope of work for improvements to the authentication lesson based on yours and other instructors' feedback. As this would be a larger amount of work, I am closing this issue for now and we will follow up with you directly with any questions we have.
